# Generated by Django 3.2.9 on 2021-12-07 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Locator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('posted', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('disabled', 'Disabled'), ('enabled', 'Enabled')], default='Enabled', max_length=10)),
                ('location', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ('posted',),
            },
        ),
    ]
